name: Node CI
run-name: Lint and Test nodejs app
on: [push]

jobs:
  lint:
    runs-on: [self-hosted]
    steps:
      - name: Descargar el repo
        uses: actions/checkout@v4
      - name: Usar nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '22.15.0'
      - name: Instalar dependencias
        working-directory: ./calculadora
        run: |
          npm install
      - name: Ejecutar Lint
        working-directory: ./calculadora
        run: |
          npm run lint
